apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 1  # Number of replicas to create
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: gitauwairimu/cmd-python-app:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: db-secret  # Mount the db-secret into environment variables
      restartPolicy: Always



# kubectl exec -it my-app-deployment-76789d8466-bxkrc -- bash
# python role_menu.py